### ISSUE TITLE
Allow Texter Servlet to Deliver Json Files

### ISSUE THREAD

**Issue by awagner-mainz** [robcast/digilib#10]
I am trying to use the Texter servlet in order to output pre-generated manifest files. (This is especially valuable in the case of multi-volume works which are represented by folders that contain only subfolders, since Manifester cannot handle such.)
For this, I have to put a manifest/collection file in the corresponding directory, but I am naming it <NameOfTheFolder>.txt. With the more conventional ".json" filename extension it does not work (and I did not even try to go by another filename/basename).

Now, the more concrete request is:
- [ ] Have the Texter servlet search for both .txt and .json files
- [ ] In case a .json file is found, set the mime-type of the reply accordingly.

(see also #11 )

**Comment by awagner-mainz** [comment]
Example: https://c104-131.cloud.gwdg.de:8443/digilib/Texter/svsal/W0013 (but this currently contains a bunch of errors...)

**Comment by robcast** [comment]
The first part of the issue should be simple. There is a filter for the type of file that gets sent by the Texter that can be extended to allow JSON.

I will move the second part of how to integrate the Manifester servlet with hand-crafted manifest files into a separate issue. It is a good idea. I will need to think about the solution a bit more.

**Comment by robcast** [comment]
closed with dc0f0da2647cac493e201d1ccd91e4ca1474e284
