### ISSUE TITLE
Manifester servlet should include existing manifest information

### ISSUE THREAD

**Issue by robcast** [robcast/digilib#11]
From #10:

There is a more general issue connected to this:
It's still a completely different path where this handcrafted manifest is found - (.../Texter/... vs. .../IIIF/...). But I cannot currently oversee whether or how these could be merged on digilib's part and what the implications of this would be...

- [ ] Maybe allow the IIIF servlet to deliver a json file, instead of generating one, if one is found at the requested path?

I would be interested to see any opinions on this.

**Comment by robcast** [comment]
I can see two solutions:
  a) if a `manifest.json` file is found in a directory it replaces the response of the Manifester servlet
  b) if a `manifest-meta.json` file is found in a directory it is merged with the automatically generated response of the Manifester servlet

Solution a) is easy to implement but it requires replacing the full manifest for a directory even if you just want to add a title or metadata block.

Solution b) is more flexible but it requires rules describing how the additional content is merged with the automatically generated content based on the image files.

**Comment by robcast** [comment]
Obviously solution a) and b) are not exclusive ;-)

Solution a) should be implemented as step one.

Step two would be solution b).  

Looking at the spec http://iiif.io/api/presentation/2.1/#resource-structure it seems that most information that you would want to customize is at the manifest level. This could be taken from the top level of the manifest-meta.json file.

It would get more complicated if you wanted to customize the canvas/page names too. Maybe this could be step three.

**Comment by awagner-mainz** [comment]
For us, it is indeed mostly manifest level information (more precisely, bibliographical metadata like author, title, license, seeAlso and such).

Another area would be structural information (chapters and articles, i.e. "ranges" I think in iiif lingo), but AFAIU, with regard to this, iiif presentation API v3 will change significantly, so it also seems not very timely to do something about it now.

**Comment by robcast** [comment]
So the manifest-level integration seems to be the most rewarding target. I'll try it out when I find some time.

The problem about anything related to canvases, be it page names or ranges, is that you have to know the canvas id beforehand. At that point the automatic generation by the Manifester does not add much anymore.
