### ISSUE TITLE
Use X-Forwarded-* HTTP headers for manifest id.

### ISSUE THREAD

**Issue by aindlq** [robcast/digilib#12]
When deployed behind reverse proxy digilb doesn't handle `X-Forwarded-*` (X-Forwarded-Host, X-Forwarded-Proto) headers and simply uses request URL as a `@id` for IIIF manifest file (see https://github.com/robcast/digilib/blob/master/servlet/src/main/java/digilib/servlet/ServletOps.java#L465).

It would be great if digilib can take de-facto standard `X-Forwarded-*`  headers into account when constructing resource `@id`

**Comment by robcast** [comment]
As far as I know the Servlet does not need to handle `X-Forwarded-*` by itself. `HttpServletRequest().getRequestURL()` should return the correctly resolved URL from the container.

I can add that it works in our setup using Tomcat on two servers behind one Apache as proxy and load balancer:
https://digilib.mpiwg-berlin.mpg.de/digitallibrary/Scaler/IIIF/permanent!library!163127KK!pageimg!0001/info.json

I only had to set `RequestHeader set X-Forwarded-Proto "https"` in Apache for https. But Tomcat handles the `X-Forwarded-*`.

Do you see different results?

**Comment by aindlq** [comment]
You are absolutely correct. I'm using jetty and there one need to explicitly enable rewrite for `X-Forwarded-*`, see http://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html#_proxy_load_balancer_connection_configuration and https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/config/etc/jetty-http-forwarded.xml

**Comment by robcast** [comment]
Now that you bring it up I remember that we had to do something to get it to work with Jetty :-)

For Jetty 8.1 we had to add `<Set name="forwarded">true</Set>` to the jetty.xml.

I should add this to the documentation (and fix the broken link in the documentation).
