### ISSUE TITLE
404 when accessing http://digilib.sourceforge.net/server-setups.html

### ISSUE THREAD

**Issue by kev1807** [robcast/digilib#15]
Hi guys, 

I was just reading about digilib and wanted to turn to server-setups, however I hit a dead end:
![grafik](https://user-images.githubusercontent.com/15955790/46650231-08eebb00-cb9c-11e8-9891-abb1d65086af.png)

I wanted to run digilib on my Raspberry Pi 3 for a test-project, however, I haven't worked with digilib, yet. (I am aiming for an IIP Imageserver that provides images for a Mirador viewer that is part of an exist-db project I am working on (a Digital Edition of some files I discovered in the National Archives in London)) 

Basic Question: Can I run digilib on my Pi (for testing purposes)? Performance is not too important, I just want to see it working, for now

**Comment by robcast** [comment]
I am sorry, the sourceforge.net pages are not maintained really well. The main documentation is on github now:

https://robcast.github.io/digilib/

Did you find the link in the documentation on github? Then I have to correct it.

The current server-setup page is now on:

https://robcast.github.io/digilib/server-setup.html

I think you should be able to run digilib on a Rapberry Pi. I have not tried it. digilib needs Java and a Tomcat server to run on port 8080 and a proxy like nginx or Apache to serve port 80 or 443.

Let me know how it goes :-)

**Comment by kev1807** [comment]
Aaah, indeed. Sorry for the trouble - everyone uses github nowadays, I should have checked first! 

I'll give it a try then, my Pi just arrived via Mail today!

**Comment by kev1807** [comment]
sadly, I can get neither Tomcat nor Jetty to run properly. I am quite confused now, having tried for 6 hours straight ... I hope I'll make progress tomorrow or on thursday ... :-/ 
(I am closing this - with further problems, such as PI-specific problems when finally running digilib, I'll create a new issue! )
