### ISSUE TITLE
[manifester] url-encode plus signs in paths

### ISSUE THREAD

**Issue by awagner-mainz** [robcast/digilib#21]
Today I found out that automatically generated manifests (for files like 'repo/ASVCCLD_001_0001+scala cromatica.jpg') refer to images without url-encoding plus signs in folder or file names. At some point in (at least) my setup,<sup>1</sup> these seems to be translated into spaces, with the result of the respective file not being found. Obviously one way around this is to avoid using pluses in filenames.

But would it be possible to have the manifester encode '+' as '%2b' automatically? (I assume characters that are more strictly "url-unsafe" are encoded anyway.)

<sup>1</sup> The setup in this case is, from user to server: mirador, chrome, caddy, digilib.

**Comment by robcast** [comment]
You seem to find all bugs with special characters in filenames ;-)

I'll check the encoding issue...

**Comment by awagner-mainz** [comment]
Cool. In my defense, I must say that I am not the one who is naming the files in the first place ;-) I will see if I manage to check out master or wait for the next release. Thank you a lot, I really do appreciate it!

**Comment by robcast** [comment]
Please try out master by building from source or use the snapshot docker image (see documentation). If you use the WAR you can try to take it out of the snapshot maven repo: https://github.com/robcast/digilib-repo/tree/gh-pages/maven-repo/digilib/digilib-webapp/2.8-SNAPSHOT
