### ISSUE TITLE
move to github CI and artifact repo

### ISSUE THREAD

**Issue by robcast** [robcast/digilib#25]
see 
https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages and
https://help.github.com/en/github/managing-packages-with-github-packages/configuring-apache-maven-for-use-with-github-packages

**Comment by robcast** [comment]
seems like github does not support SNAPSHOT releases yet :-(
(https://help.github.com/en/github/managing-packages-with-github-packages/configuring-apache-maven-for-use-with-github-packages)

**Comment by aindlq** [comment]
jfyi, you can't use github packages without authentication, like you can use maven central, npm, docker hub, etc - https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888/highlight/true#M1294

**Comment by robcast** [comment]
Oh dear. Packages seems not to be ready for prime time...

**Comment by robcast** [comment]
CI moved to Github actions. Maven repo still homegrown...
