### ISSUE TITLE
better OOM handling

### ISSUE THREAD

**Issue by robcast** [robcast/digilib#28]
digilib should return and log an error if it runs out of memory.

Can we just catch OOM exceptions? What can we still do then?

**Comment by funkyfuture** [comment]
> What can we still do then?

a restart should be fine.

**Comment by robcast** [comment]
> > What can we still do then?
> 
> a restart should be fine.

System.exit() seems overly harsh as a general action. In most cases (I have not done systematic tests) only the current request dies, following requests seem to continue to work fine.

I would prefer just to catch the exception, abort the processing and return an error.
