### ISSUE TITLE
Use current application directory for relative path resolution in `basedir-list`

### ISSUE THREAD

**Issue by aindlq** [robcast/digilib#35]
Use case: we want to distribute ResearchSpace in a simple bundle with jetty, digilib, blazegraph and have digilib basedir-list by default pointing to some folder inside the bundle. Actually I've already done that with some hard-coded change in digilib, but I would prefer to use official build instead of my own one.

If I understand correctly, currently relative path is resolved against `ServletContext` root, so it is possible to use only relative path that is inside webapp (in `ServletOps#getFile`), right?

Would it be OK to introduce new configuration property that just use path as is and resort to java default behavior of using current application directory aka `user.dir`? I can submit PR if you are fine with that.

**Comment by robcast** [comment]
This sounds like a good idea. I was never really sure what the best base directory for a web application would be so I chose the ServletContext.

How is `user.dir` set for a web application? Does it depend on the servlet container?

I am fine with a new solution as long as there is still a way to target the demo image folder inside the web application for the demo app :-)

**Comment by aindlq** [comment]
> How is user.dir set for a web application? Does it depend on the servlet container?
It works the same for any java application, it is the folder where `java` command is executed. This is default behavior for relative path resolution if you do `new File("./relative-path")`

> I am fine with a new solution as long as there is still a way to target the demo image folder inside the web application for the demo app :-)
See my PR, the old behavior is preserved.
