### ISSUE TITLE
outdated configuration docs

### ISSUE THREAD

**Issue by funkyfuture** [robcast/digilib#4]
the documentation of the available [configuration options](http://digilib.sourceforge.net/digilib-config.html) lacks some that are actually available, this are at least these:

- `docuimage-class`
- `subsample-minimum`
- `worker-timeout`
- `filemeta-class`
- `dirmeta-class`
- `authops-class`
- `worker-timeout`
- `authops-class`
- `auth-file`
- `auth-url-path`
- `img-diskcache-allowed`
- `iiif-prefix`

the following options are listed, but reading the docs don't make (fully) clear what these are about:

- `default-quality` (what would be the maximum value?)
- `use-mapping`
- `mapping-file`

from an administrator's perspective that is not satisfactory, neither is a recommendation to read the source code. a central document that lists all options and describes them sufficiently is an accessible, helpful 'gateway'.

for a better reading experience i propose to group configuration options by domains and link to relevant documents in these sections. e.g., a section with a list of iiif-related options and a link to `iiif-api.html`.

i can provide a refactoring and extension (as far as i'm competent)  of the `digilib-config.md` if this proposal is accepted.

**Comment by robcast** [comment]
Documentation of the configuration options always was a weak spot. (I always tend to spend more time writing code than documentation.)

I would really like to see a new structure for the config documentation. If you would propose a structure I could fill in the details.

**Comment by robcast** [comment]
I merged your PR and updated the config doc. There are still lots of config options left to document but I think this is a good first step.
I also added your nginx-docu to the main menu. I still need to add Apache config to that one.

**Comment by robcast** [comment]
I updated the digilib-config doc again and I think I now have documented all major options.
