### ISSUE TITLE
Problem with the rotation of images

### ISSUE THREAD

**Issue by claushfranke** [robcast/digilib#62]
Hello,

we have encountered a problem with digilib regarding the output when the image is rotated through digilib:

If you rotate the image via the parameter "rot" a second layer is created. In the front one the image is displayed correctly. The rear one displays the rotated image distorted. The back layer looks like the rotated image, which was only fitted into the image in width but not in height. By simply zooming in and out, the front layer is removed and only the back layer is visible. 

Here is an example link from our site:
https://digilib.bbaw.de/digilib/digilib.html?dw=1858&dh=912&fn=silo10/thrakien/coins/apollonia_ad_ryn_ae10-62_g-_25-1_mm-_7_h_as_01.jpg&ww=0.7143&wh=0.7143&wx=0.1429&wy=0.1429&mo=png&rot=11

Adding the parameter "mo=jpg" fixes the problem, but sets the background color to black which is not so nice. 

Is there a possibility to define the background color, so that the output as jpg would be okay? Or is there any way to fix the png output?

Thank you,
Claus

**Comment by robcast** [comment]
There have always been some issues with the background image and rotations that are not multiples of 90°. The background image is normally used as a "preview" when moving the image area but the size calculations are wrong when the image is slightly rotated.

I'll look into the problem. Maybe we should just disable the background when the image is rotated.

**Comment by claushfranke** [comment]
If it is possible to deactivate the background image, that would be a possibility.

**Comment by robcast** [comment]
I have created a new release 2.12.3 with the simple fix of disabling the preview background for some rotations.

There are still some issues when zooming and panning rotated images. We need a better approach to calculate the image transformation when the image is bigger as expected due to oblique rotation angle.

**Comment by claushfranke** [comment]
Hello, thank you for your good and fast work. We have applied the update. Now the wrong background is gone. Would it still be possible to define the background color via a parameter. Currently the free space created by the rotation is filled with black (jpg) or gray (png). I suspect that the gray is actually a transparent black (scalerFadedOpacity' : 0.6).

We embed the images on our site via Digilib and use that tool to not have to change the original state.

**Comment by claushfranke** [comment]
Here is a small example for this behavior: https://digilib.bbaw.de/digilib/digilib.html?dw=1826&dh=880&fn=silo10/thrakien/coins/apollonia_ad_ryn_ae10-62_g-_25-1_mm-_7_h_as_01.jpg&mo=jpg&rot=11

**Comment by robcast** [comment]
@claushfranke the background of the central image element in the HTML frontend is defined as "gray" in the CSS:
```css
div.dl-digilib div.dl-scaler {
  background-color: gray;
}
```
You should be able to overrride it for your installation. The background is only visible if the image itself has transparency which is not possible in JPEG.
